Jaimec branch
Schots/mlops_project pull request #2
Opened 2022-01-19 12:13 UTC by JaimeCirilo

Alteração do arquivo README explicando como instalar, clonar e dar push no GITHUB (Windows).

2022-01-19 12:35 UTC, Schots requested changes

2022-01-19 12:35 UTC, Schots commented on README.md
> +
Os comandos que vc descreve valem para linux tb.

2022-01-19 12:35 UTC, Schots commented on README.md
> +     3º O prompt irá solicitar login e senha da conta do github pelo próprio prompt, é só inserir e o push será feito.
Tá confuso ainda o texto. Quando clono um projeto eu já obtenho um repositório local, portanto não preciso de git init.

2022-01-19 12:44 UTC, JaimeCirilo commented on README.md
> +     3º O prompt irá solicitar login e senha da conta do github pelo próprio prompt, é só inserir e o push será feito.
Irei melhorar o texto e fazer um novo push.

2022-01-22 14:51 UTC, Schots commented
Fechado por inatividade > 3 dias.

2022-01-22 14:51 UTC, closed without merging