feat: adds a dvc reproducible pipeline
Schots/mlops_project pull request #65
Opened 2022-02-08 18:24 UTC by maikereis

2022-02-08 22:28 UTC, Schots requested changes

2022-02-08 22:28 UTC, Schots commented on dvc.yaml
> +    cmd: python3 download_dataset.py -d titanic
Cria alvos no Makefile pra cada cmd. A ideia central do nosso projeto é controlar execuções de comandos por lá.

2022-02-08 22:28 UTC, Schots commented on src/prepare/prepare_data.py
> +x_test_in = test_in
“Survived” tá hard coded. A ideia é eliminar qualquer código específico. Nossas pipelines têm que ser customizáveis por arquivos de configuração.

2022-02-08 22:31 UTC, Schots commented on src/prepare/prepare_data.py
> +x_test_in = test_in
Andei olhando a nova documentação DVC. Cria um arquivo de configuração params.yaml (nome default)

2022-02-09 00:19 UTC, Schots requested changes

2022-02-09 00:19 UTC, Schots commented on Makefile
> -	@dvc repro make_data
Troca o nome do alvo por dataset, por favor.

2022-02-09 00:24 UTC, maikereis commented on Makefile
> -	@dvc repro make_data
Mas isso não existe mais

2022-02-09 00:27 UTC, Schots approved these changes

2022-02-09 00:28 UTC, merged